# Generated by Django 4.0.5 on 2022-06-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='details',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
