# Generated by Django 4.0.5 on 2022-06-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.CharField(choices=[('Bakery', 'Bakery'), ('Meat&Seafood', 'Meat&Seafood'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Dairy', 'Dairy')], default=None, max_length=100),
        ),
    ]
